# Generated by Django 2.1.4 on 2020-03-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('childname', models.CharField(max_length=20)),
                ('bloodgroup', models.CharField(max_length=20)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='CharityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Contact_No', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('Occupation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DonationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Charity_id', models.IntegerField(blank=True, null=True)),
                ('Donation_Amt', models.IntegerField()),
                ('Donation_things', models.CharField(max_length=20)),
                ('Donation_date', models.DateField()),
                ('purpes', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Homevstngstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplnNo', models.IntegerField()),
                ('visited_date', models.DateField()),
                ('doc_verification', models.CharField(max_length=20)),
                ('visiting_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrphanageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_Name', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('JoiningYear', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrphnHltSts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_id', models.CharField(max_length=20)),
                ('Health_problems', models.CharField(max_length=20)),
                ('last_checkup_date', models.DateField()),
                ('Previous_checkupdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_name', models.CharField(max_length=20)),
                ('Husband_wife_name', models.CharField(max_length=40)),
                ('education', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('Photo', models.CharField(max_length=20)),
                ('Marriage_certificate', models.CharField(max_length=20)),
                ('Phone_No', models.IntegerField()),
                ('Application_No', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requeststatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appln_no', models.IntegerField(blank=True, null=True)),
                ('requeststatus', models.CharField(max_length=20)),
                ('requestdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SurityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplnNo', models.IntegerField()),
                ('Surity_amount', models.IntegerField()),
                ('Surity_duration', models.CharField(max_length=20)),
                ('terms_conditions', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('utype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
