# Generated by Django 2.1.4 on 2020-04-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionapp', '0002_parentreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentreg',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
