# Generated by Django 2.1.4 on 2020-04-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionapp', '0003_parentreg_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babyinfo',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babyinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
