# Generated by Django 2.1.4 on 2020-04-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionapp', '0004_auto_20200402_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('request_by', models.CharField(max_length=100)),
                ('request_date', models.DateField()),
                ('adoption_reason', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('family_members', models.CharField(max_length=20)),
                ('annual_income', models.CharField(max_length=11)),
                ('assets', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
