# Generated by Django 2.1.4 on 2020-04-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionapp', '0006_adoptionrequest_baby_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentsinfo',
            name='Husband_wife_name',
        ),
        migrations.RemoveField(
            model_name='parentsinfo',
            name='Phone_No',
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='Husband_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='parent_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentsinfo',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='Applicant_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='Email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='Marriage_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentsinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
