# Generated by Django 2.1.4 on 2020-04-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionapp', '0007_auto_20200402_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststatus',
            name='adoptionstatus',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='requeststatus',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
