# Generated by Django 2.1.4 on 2020-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionapp', '0009_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsinfo',
            name='aadhar_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
