# Generated by Django 2.1.4 on 2020-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionapp', '0011_auto_20200515_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
