# Generated by Django 2.1.4 on 2020-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionapp', '0012_adoptionrequest_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyinfo',
            name='adoption_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
