# Generated by Django 2.1.4 on 2020-05-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionapp', '0013_babyinfo_adoption_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
